name: CITest

on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:    
      matrix:
        cc: [gcc, clang]
        os: [ubuntu-latest, macos-latest]
        #exclude:
        #  - os: macos-latest
        #    cc: clang

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      env:
        CC: ${{ matrix.cc }}
    - name: config cmake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: test base
      working-directory: ${{github.workspace}}/test/bin
      run: |
        ./cpptest
        ./lua53

    - name: test genProto
      if: runner.os == 'Linux'
      working-directory: ${{github.workspace}}/test/genCode
      run: |
        ./genProto

    - name: test genProtoMac
      if: runner.os == 'macOS'
      working-directory: ${{github.workspace}}/test/genCode
      run: |
        ./genProtoMac


      
